### PR TITLE
Upgrade uno

### PR DESCRIPTION
**Pull request by kusma**
There's some incompatible / obosolete changes in Uno, making this update not entirely trivial. So here's a separate PR to fix that.

### CODE REVIEW

**Comment by kusma** [comment]
@mortoray: Indeed. I was really just applying the changes that the uno-compiler produced, but I was also slightly involved in the PR on Uno that did this change, so I was kind of aware that this was coming ;)

**Comment by yupferris** [comment]
Other than the `InternalsVisibleTo` that was missing, is there anything that's actually incompatible, or just deprecated stuff we're changing in here for later?

**Comment by kusma** [comment]
@yupferris: The rest is just about removing new warnings.

**Comment by yupferris** [comment]
gotcha

**Pull request merged**
