### PR TITLE
Fuse.Controls.Video: don't use WPF assemblies on mono/macOS

### PR DESCRIPTION
**Pull request by mortend**
Try avoiding having to find "PresentationCore" since that's a WPF assembly only found on Windows,
https://github.com/fusetools/uno/issues/1464

This PR contains:
- [ ] Changelog
- [ ] Documentation
- [ ] Tests

### CODE REVIEW

**Comment by kusma** [comment]
@mortend: I wish we could have changed uno to not need this instead, because I'm afraid of 3rd party code doing the same... :/

**Comment by kusma** [comment]
Sadly, it doesn't fix the problem for me, I now get this instead:
```
You are using dlopen without a full path, retrying by prepending /usr/lib
Could not find `Fuse.Video.WPF` referenced by assembly `Fuse.Video.CIL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`.
Could not find `Fuse.Video.WPF` referenced by assembly `ManualTestingApp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`.
Could not find `Fuse.Video.WPF` referenced by assembly `ManualTestingApp-loader, Version=0.0.65535.65535, Culture=neutral, PublicKeyToken=null`.
System.IO.FileNotFoundException: Could not load file or assembly 'Fuse.Video.WPF' or one of its dependencies
File name: 'Fuse.Video.WPF'
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity) <0x109fa2010 + 0x00489> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (System.Reflection.AssemblyName,System.Security.Policy.Evidence)
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef) <0x109fa1ef0 + 0x00022> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.AppDomain:Load (System.Reflection.AssemblyName)
  at System.Reflection.Assembly.Load (System.Reflection.AssemblyName assemblyRef) <0x109fa1df0 + 0x0002b> in <filename unknown>:0 
  at ObjCRuntime.Runtime.CollectReferencedAssemblies (System.Collections.Generic.List`1 assemblies, System.Reflection.Assembly assembly) <0x109fa1a80 + 0x000a8> in <filename unknown>:0 
```

**Comment by mortoray** [comment]
@kusma Do you know if we can close this now or does it need to be picked up by somebody?

**Comment by kusma** [comment]
It can be closed, thanks for the reminder!

**Pull request closed without merging**
