### PR TITLE
Fixes Activation and EdgeNavigator

### PR DESCRIPTION
**Pull request by mortoray**
I'm not entirely happy with how I fixed EdgeNavigator but I saw no other simple short-term solution, especially not for a hotfix. A lot of the clarified stuff was undefined before, so it shouldn't be backwards incompatible. Some stuff is still undefined unfortunately.

fixes https://github.com/fusetools/fuselibs-public/issues/223

This PR contains:
- [x] Changelog
- [x] Tests

### CODE REVIEW

**Comment by kusma** [comment]
@mortoray: This fails a test:

> FAILED:  Fuse.Gestures.Test.Fuse.Gestures.Test.GestureTest.Layer
>         Assertion failed in 'Layer', at C:\projects\fuselibs-public\Source\Fuse.Gestures\Tests\Gesture.Test.uno:31
>           Expected: null
>           But got : Fuse.Controls.PageControl, Name: edgeMain

**Comment by mortoray** [comment]
@kusma I'd expect that test to fail, it needs to be fixed... but it's not on the 1.1 branch. Ah. I marked the PR incorrectly. I'll update the PR's merge target.

**Comment by mortoray** [comment]
@kusma How do I trigger a rerun after changing the target branch?

And how can I deal with fixing the test on `master`? Will you just let me know once you merge back to master and I can fix it?

**Comment by mortoray** [comment]
Travis has the base branch confused.

**Pull request closed without merging**
