### PR TITLE
Fix idleness in ThreadWorker when using setTimeout( func, 0)

### PR DESCRIPTION
**Pull request by nekronos**
This PR contains:
- [x] Changelog
- [ ] Documentation
- [x] Tests

### CODE REVIEW

**Comment by nekronos** [comment]
@mortoray maybe? This is part of https://github.com/fusetools/fuselibs-public/pull/601, but doing it as a separate PR

**Comment by kusma** [comment]
I think 6bca8da3eec667cd89dd8670b2c6c2c6c5ec074b should be squashed in here. Also, we should make a test-case for this.

**Comment by mortoray** [comment]
Ah, I didn't realize this was on that branch where I did it.

**Comment by nekronos** [comment]
From a quick look at the code I think writing meaningful tests would involve larger changes to `ThreadWorker`/`Timer` to make the code testable

**Comment by kusma** [comment]
@nekronos: How so? Can't we just use a reasonably large timeout, and wait a reasonable amount of time?

**Comment by nekronos** [comment]
Again, I dont know this code. Just looked like it would require some refactoring to make stuff testable as units. The `Timer`, `ThreadWorker` looks pretty coupled to `JSContext`

**Comment by mortoray** [comment]
You could test the Test functions in the ThreadWorker class. THere are some exposed to check if the thread is idle. You could set a large timeout in JS and then check that it isn't idle. Of course, I don't know how you'd check when it is again. A short timetout would also cause a race condition.

**Comment by kusma** [comment]
@nekronos: Perhaps this should be mentioned in the changelog? Or do you think it's insignificant enough to "normal" users to omit?

**Comment by nekronos** [comment]
yeah, lets add some changelog

**Pull request merged**
