### PR TITLE
Attempt at unbreaking the map documentation

### PR DESCRIPTION
**Pull request by petterroea**

### CODE REVIEW

**Comment by kusma** [comment]
I don't understand this. It's an *attempt*? Do we not know if it works or not?

**Comment by kusma** [comment]
By the way, the change looks completely bogus to me...

**Comment by petterroea** [comment]
Since this is in the fuselibs repo, i have no way as far as i know of verifying that it works.

**Comment by kusma** [comment]
@petterroea: Surely you can run the docs-generator yourself, no?

**Comment by petterroea** [comment]
Yes, but the way the docs-generator is set up, it pulls in precrunched data from fuselibs. I will investigate the possibility of building fuselibs-docs locally.

**Comment by sebbert** [comment]
@kusma Verified locally in https://github.com/fusetools/fuselibs-public/pull/116

**Comment by kusma** [comment]
@sebbert: I'm not sure I understand. #116 is different than this. Does that mean that this one did not work as-is?

**Comment by sebbert** [comment]
@kusma This pull request (#104) produces invalid output. Since I can't push directly to the branch this is based on, I fixed the issue separately, verified the result, and put it in #106

**Comment by kusma** [comment]
OK, then I'll close this one.

**Pull request closed without merging**
