### PR TITLE
Allow NameValuePairs to have expression for names.

### PR DESCRIPTION
**Pull request by Duckers**
Needs new Uno stuff with https://github.com/fusetools/uno/pull/1235

### CODE REVIEW

**Comment by kusma** [comment]
> Source/Fuse.Reactive.JavaScript/Tests/UX/NameValuePair.ux(9): E8001: Sequence contains no matching element

This sounds like it revealed a bug in the UX-compiler...

**Comment by Duckers** [comment]
woops, on it!

**Comment by kusma** [comment]
Also, why was the checklist removed from the PR-template? It's meant to make sure these things are considered, and tests are certainly appropriate in this case.

**Comment by Duckers** [comment]
Superceded by the above PR

**Pull request closed without merging**
