### PR TITLE
ImageSource: added Transform property

### PR DESCRIPTION
**Pull request by nekronos**
Useful for ImageSources that needs to be transformed to display
correctly. For example photos captured with frontfacing camera

This PR contains:
- [x] Changelog
- [ ] Documentation
- [ ] Tests

### CODE REVIEW

**Comment by kusma** [comment]
Can't the same thing already be done by modifying `Source.Orientation` instead?

**Comment by nekronos** [comment]
[`Source.Orientation`](https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Elements/Resources/Exif/Exif.uno#L12) is based on EXIF and cannot provide a custom transform.

Although, in my usecase the textures from camera are mirrored, so `ImageOrientation` could be changed to be general and I can add mirroring as a flag

**Comment by mortoray** [comment]
I think extended `Orientation` would also make sense here. General purpose transforms on ImageSource would have unintended consequences for layout/drawing/render calculations.

**Comment by kusma** [comment]
@nekronos: `Source.Orientation` can already express all flipping and 90-degress rotation variations. You'll have to combine vertical flipping and 180 degree rotation to do horizontal flipping (or mirroring as you call it).

**Comment by mortoray** [comment]
@nekronos Are you going to change the approach here to use the existing orientation as Erik describes?  Can this PR be closed?

**Comment by mortoray** [comment]
I'll assume the lack of activity means this has been merged elsewhere, or a new approach has been used. I'll close this.

**Pull request closed without merging**
