### PR TITLE
Feature Tree Observable

### PR DESCRIPTION
**Pull request by nekronos**
Fixed history

This PR contains:
- [ ] Changelog
- [ ] Documentation
- [ ] Tests

### CODE REVIEW

**Comment by kusma** [comment]
So, if I understand the situation correctly, this is the same version of the PR that got merged, but broke integration-tests with the tool, and hung tests at startup for the MSVC-target.

**Comment by nekronos** [comment]
@kusma yes, still need to resolve those problems. Had to fix some broken git history with https://github.com/fusetools/fuselibs-public/pull/601. This PR and https://github.com/fusetools/fuselibs-public/pull/601 is now properly in-sync

**Comment by nekronos** [comment]
@kusma this is now building on TC https://tc.outracks.com/viewLog.html?buildId=698600&tab=queuedBuildOverviewTab
Should we try merge again? :)

**Comment by kusma** [comment]
@nekronos: Yeah, but let's wait until 1.4 has been branched out. That's happening today.

**Pull request merged**
