### PR TITLE
fixes PageControl.ActiveIndex

### PR DESCRIPTION
**Pull request by mortoray**
fixes https://github.com/fusetools/fuselibs-public/issues/614

@kusma This fixes a regression in 1.3, so at the very least it should be in 1.4, or if there is planned 1.3 release then there.

This PR contains:
- [x] Changelog
- [ ] ~Documentation~
- [x] Tests

### CODE REVIEW

**Comment by kusma** [comment]
@mortoray: OK, thanks for the heads up. This means this should at least be pulled against 1.4, and we should also consider doing a 1.3.1 IMO. But the latter is of course a bigger question that more people needs to be involved in.

**Comment by mortoray** [comment]
I don't think this alone would justify a 1.3.1. The defect appears as part of a feature (Pagecontrol with dynamic pages) that was previously littered with defects and problems -- limiting it's use, thus limiting the impact of the defect. The rewrite of this code in 1.3 fixed a lot of those issues (but obviously introduced this one).

**Comment by kusma** [comment]
Well, the common wisdom is that for every user who reports a bug, there's a bunch who doesn't. I think if we know that we break something in an actively maintained release, we should fix it. It's not a lot of work.

**Comment by bentstamnes** [comment]
> Well, the common wisdom is that for every user who reports a bug, there's a bunch who doesn't.

I believe the ratio is 1:26 (for every single report, there are 26 that that experience the same issue but don't know how or don't bother to report it)

**Comment by mortoray** [comment]
Yes, I know that's the normal case, I just mean because the feature-set was flaky before, the rate of use was likely more limited than a functioning feature.

**Comment by kusma** [comment]
@mortoray: Yikes: https://ci.appveyor.com/project/fusetools/fuselibs-public/build/1689#L438

**Pull request merged**
