### PR TITLE
fixes invalid page reuse for context based pages (1.6 version)

### PR DESCRIPTION
**Pull request by mortoray**
*NOTE*: This fix has been merged into master already. We considered it too risky for 1.6 for now, but it remains here in case it becomes a more serious problem.

rebase on release-1.6 based on @duckers request

This replaces https://github.com/fusetools/fuselibs-public/pull/946

This PR contains:
- [x] Changelog
- [ ] ~Documentation~
- [x] Tests

### CODE REVIEW

**Comment by Duckers** [comment]
This PR is pretty much required in order to use Models meaningfully with Navigation

**Comment by nekronos** [comment]
@mortoray please rebase

**Comment by mortoray** [comment]
@nekronos Rebased on release-1.6

**Comment by nekronos** [comment]
Closing since we have branched out `release-1.7`

**Pull request closed without merging**
