### PR TITLE
Fix models after 1.6 merge

### PR DESCRIPTION
**Pull request by sebbert**
This fixes models tests after they broke when merging `release-1.6` to `master`.

This PR contains:
- [ ] Changelog
- [ ] Documentation
- [x] Tests

### CODE REVIEW

**Comment by mortoray** [comment]
@sebbert Hmm, it shouldn't have been broken... note that the deprecated warnings in unit tests will cause the test to fail. Did you see the deprecated warning in the output?

**Comment by sebbert** [comment]
@mortoray No, I get the following. Smells like a regression :/

```
FAILED:  Fuse.Models.Test.Fuse.Models.Test.ModelTest.NestedArray
         Exception was thrown: System.Exception: Incomplete or duplicate unrooting: Fuse.Reactive.Each/
   at Fuse.Node.UnrootInternal() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Node.Rooting.uno:line 156
   at Fuse.Node.Unrelate(Visual parent, Node child) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Node.Rooting.uno:line 192
   at Fuse.Visual.OnRemoved(Node b) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Visual.Children.uno:line 149
   at Fuse.Visual.Remove(Node item) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Visual.Children.uno:line 189
   at Fuse.Visual.BeginRemoveChild(Node n, Action`1 then) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Visual.BeginRemove.uno:line 102
   at Fuse.Reactive.Instantiator.RemoveFromParent(Node n) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Reactive.Bindings\Instantiator.uno:line 166
   at Fuse.Reactive.Instantiator.CleanupWindowItem(WindowItem wi) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Reactive.Bindings\Instantiator.uno:line 763
   at Fuse.Reactive.Instantiator.DisposeWindowItem(WindowItem wi) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Reactive.Bindings\Instantiator.uno:line 756
   at Fuse.Reactive.Instantiator.RemoveAvailableItems() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Reactive.Bindings\Instantiator.uno:line 738
   at Fuse.Reactive.Instantiator.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Reactive.Bindings\Instantiator.uno:line 139
   at Fuse.Node.UnrootInternal() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Node.Rooting.uno:line 161
   at Fuse.Visual.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Visual.uno:line 155
   at Fuse.Elements.Element.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Elements\Element.Node.uno:line 50
   at Fuse.Controls.Control.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Controls\Control.Background.uno:line 91
   at Fuse.Controls.LayoutControl.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Controls.Panels\LayoutControl.uno:line 126
   at Fuse.Controls.Panel.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Controls.Panels\Panel.uno:line 79
   at Fuse.Node.UnrootInternal() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Node.Rooting.uno:line 161
   at Fuse.Visual.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Visual.uno:line 155
   at Fuse.Elements.Element.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Elements\Element.Node.uno:line 50
   at Fuse.Controls.Control.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Controls\Control.Background.uno:line 91
   at Fuse.Controls.LayoutControl.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Controls.Panels\LayoutControl.uno:line 126
   at Fuse.Controls.Panel.OnUnrooted() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Controls.Panels\Panel.uno:line 79
   at Fuse.Node.UnrootInternal() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Node.Rooting.uno:line 161
   at Fuse.Node.Unrelate(Visual parent, Node child) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Node.Rooting.uno:line 192
   at Fuse.Visual.OnRemoved(Node b) in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Visual.Children.uno:line 149
   at Fuse.Visual.Uno.Collections.ICollection<Fuse.Node>.Clear() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\Visual.Children.uno:line 172
   at Fuse.RootViewport.Uno.IDisposable.Dispose() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Nodes\RootViewport.uno:line 95
   at FuseTest.TestRootPanel.Uno.IDisposable.Dispose() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Common\Tests\FuseTest\TestRootNode.uno:line 60
   at Fuse.Models.Test.ModelTest.NestedArray() in C:\Users\Sebbert\code\uno\lib\fuselibs\Source\Fuse.Models\Tests\Model.Test.uno:line 18
   at MainClass.Invoke___Fuse_Models_Test_ModelTest_NestedArray()
   at Uno.Testing.AbstractRunner.RunTest(NamedTestMethod test) in C:\Users\Sebbert\code\uno\Library\Core\Uno.Testing\AbstractRunner.uno:line 109
```

**Comment by mortoray** [comment]
That could still be a Deprecation warning, they cause funny things to happen when you're not exepcting them in a test.

I'm going to confirm this for now on that suspicion. I have tests that explciitly check that `{}` still works, so it should be fine here.

**Comment by sebbert** [comment]
Alright, should be fine then 👍

**Pull request merged**
