### PR TITLE
fixed an issue with this test, a merge in 1.1 changed how EdgeNAvigat…

### PR DESCRIPTION
**Pull request by mortoray**
fixes https://github.com/fusetools/fuselibs-public/issues/247

This PR contains:
- [x] Tests

### CODE REVIEW

**Comment by kusma** [comment]
I think we also need this no release-1.2...

**Comment by kusma** [comment]
@mortoray: Sorry if I'm being very forgetful here, but did we get this on release-1.2 as well? I can't find any traces of that... If not, could you please back-port this PR there?

**Comment by mortoray** [comment]
@kusma There is another PR for 1.2 https://github.com/fusetools/fuselibs-public/pull/259 that has a commit with the same fix.

**Comment by kusma** [comment]
Ah, never mind. This is a test, and it passes on release-1.2, so I guess everything is fine.

**Pull request merged**
